language: node_js
node_js:
  - node
script:
  - yarn lint:js
  - yarn lint:css
  - yarn run build
  - yarn run build:storybook
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/storybook
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    node_js: 'node'
