export const simpleItems = [
  { label: 'Neptunium', value: 'Neptunium', id: 1 },
  { label: 'Plutonium', value: 'Plutonium', id: 2 },
  { label: 'Americium', value: 'Americium', id: 3 },
  { label: 'Curium', value: 'Curium', id: 4 },
  { label: 'Berkelium', value: 'Berkelium', id: 5 },
  {
    label: 'Californium Berkelium Curium Plutonium',
    value: 'Californium Berkelium Curium Plutonium',
    id: 6,
  },
  { label: 'Einsteinium', value: 'Einsteinium', id: 7 },
  { label: 'Fermium', value: 'Fermium', id: 8 },
  { label: 'Mendelevium', value: 'Mendelevium', id: 9 },
  { label: 'Nobelium', value: 'Nobelium', id: 10 },
  { label: 'Lawrencium', value: 'Lawrencium', id: 11 },
  { label: 'Rutherfordium', value: 'Rutherfordium', id: 12 },
  { label: 'Dubnium', value: 'Dubnium', id: 13 },
  { label: 'Seaborgium', value: 'Seaborgium', id: 14 },
  { label: 'Bohrium', value: 'Bohrium', id: 15 },
  { label: 'Hassium', value: 'Hassium', id: 16 },
  { label: 'Meitnerium', value: 'Meitnerium', id: 17 },
  { label: 'Darmstadtium', value: 'Darmstadtium', id: 18 },
  { label: 'Roentgenium', value: 'Roentgenium', id: 19 },
  { label: 'Copernicium', value: 'Copernicium', id: 20 },
  { label: 'Nihonium', value: 'Nihonium', id: 21 },
  { label: 'Flerovium', value: 'Flerovium', id: 22 },
  { label: 'Moscovium', value: 'Moscovium', id: 23 },
  { label: 'Livermorium', value: 'Livermorium', id: 24 },
  { label: 'Tennessine', value: 'Tennessine', id: 25 },
  { label: 'Oganesson', value: 'Oganesson', id: 26 },
];

export const groups = [
  {
    label: 'First',
    items: [
      { label: 'Neptunium', value: 'Neptunium', id: 1 },
      { label: 'Plutonium', value: 'Plutonium', id: 2 },
      { label: 'Americium', value: 'Americium', id: 3 },
      { label: 'Curium', value: 'Curium', id: 4 },
      { label: 'Berkelium', value: 'Berkelium', id: 5 },
    ],
  },
  {
    label: 'Second',
    items: [
      {
        label: 'Californium Berkelium Curium Plutonium',
        value: 'Californium Berkelium Curium Plutonium',
        id: 6,
      },
      { label: 'Einsteinium', value: 'Einsteinium', id: 7 },
      { label: 'Fermium', value: 'Fermium', id: 8 },
      { label: 'Mendelevium', value: 'Mendelevium', id: 9 },
      { label: 'Nobelium', value: 'Nobelium', id: 10 },
      { label: 'Lawrencium', value: 'Lawrencium', id: 11 },
      { label: 'Rutherfordium', value: 'Rutherfordium', id: 12 },
      { label: 'Dubnium', value: 'Dubnium', id: 13 },
      { label: 'Seaborgium', value: 'Seaborgium', id: 14 },
    ],
  },
  {
    label: 'Third',
    items: [
      { label: 'Bohrium', value: 'Bohrium', id: 15 },
      { label: 'Hassium', value: 'Hassium', id: 16 },
      { label: 'Meitnerium', value: 'Meitnerium', id: 17 },
      { label: 'Darmstadtium', value: 'Darmstadtium', id: 18 },
      { label: 'Roentgenium', value: 'Roentgenium', id: 19 },
      { label: 'Copernicium', value: 'Copernicium', id: 20 },
      { label: 'Nihonium', value: 'Nihonium', id: 21 },
      { label: 'Flerovium', value: 'Flerovium', id: 22 },
    ],
  },
  {
    label: 'Four',
    items: [
      { label: 'Moscovium', value: 'Moscovium', id: 23 },
      { label: 'Livermorium', value: 'Livermorium', id: 24 },
      { label: 'Tennessine', value: 'Tennessine', id: 25 },
      { label: 'Oganesson', value: 'Oganesson', id: 26 },
    ],
  },
];
