export const simpleItems = [
  { label: 'Neptunium', value: 'Neptunium' },
  { label: 'Plutonium', value: 'Plutonium' },
  { label: 'Americium', value: 'Americium' },
  { label: 'Curium', value: 'Curium' },
  { label: 'Berkelium', value: 'Berkelium' },
  {
    label: 'Californium Berkelium Curium Plutonium',
    value: 'Californium Berkelium Curium Plutonium',
  },
  { label: 'Einsteinium', value: 'Einsteinium' },
  { label: 'Fermium', value: 'Fermium' },
  { label: 'Mendelevium', value: 'Mendelevium' },
  { label: 'Nobelium', value: 'Nobelium' },
  { label: 'Lawrencium', value: 'Lawrencium' },
  { label: 'Rutherfordium', value: 'Rutherfordium' },
  { label: 'Dubnium', value: 'Dubnium' },
  { label: 'Seaborgium', value: 'Seaborgium' },
  { label: 'Bohrium', value: 'Bohrium' },
  { label: 'Hassium', value: 'Hassium' },
  { label: 'Meitnerium', value: 'Meitnerium' },
  { label: 'Darmstadtium', value: 'Darmstadtium' },
  { label: 'Roentgenium', value: 'Roentgenium' },
  { label: 'Copernicium', value: 'Copernicium' },
  { label: 'Nihonium', value: 'Nihonium' },
  { label: 'Flerovium', value: 'Flerovium' },
  { label: 'Moscovium', value: 'Moscovium' },
  { label: 'Livermorium', value: 'Livermorium' },
  { label: 'Tennessine', value: 'Tennessine' },
  { label: 'Oganesson', value: 'Oganesson' },
];

export const groups = [
  {
    label: 'First',
    items: [
      { label: 'Neptunium', value: 'Neptunium' },
      { label: 'Plutonium', value: 'Plutonium' },
      { label: 'Americium', value: 'Americium' },
      { label: 'Curium', value: 'Curium' },
      { label: 'Berkelium', value: 'Berkelium' },
    ],
  },
  {
    label: 'Second',
    items: [
      {
        label: 'Californium Berkelium Curium Plutonium',
        value: 'Californium Berkelium Curium Plutonium',
      },
      { label: 'Einsteinium', value: 'Einsteinium' },
      { label: 'Fermium', value: 'Fermium' },
      { label: 'Mendelevium', value: 'Mendelevium' },
      { label: 'Nobelium', value: 'Nobelium' },
      { label: 'Lawrencium', value: 'Lawrencium' },
      { label: 'Rutherfordium', value: 'Rutherfordium' },
      { label: 'Dubnium', value: 'Dubnium' },
      { label: 'Seaborgium', value: 'Seaborgium' },
    ],
  },
  {
    label: 'Third',
    items: [
      { label: 'Bohrium', value: 'Bohrium' },
      { label: 'Hassium', value: 'Hassium' },
      { label: 'Meitnerium', value: 'Meitnerium' },
      { label: 'Darmstadtium', value: 'Darmstadtium' },
      { label: 'Roentgenium', value: 'Roentgenium' },
      { label: 'Copernicium', value: 'Copernicium' },
      { label: 'Nihonium', value: 'Nihonium' },
      { label: 'Flerovium', value: 'Flerovium' },
    ],
  },
  {
    label: 'Four',
    items: [
      { label: 'Moscovium', value: 'Moscovium' },
      { label: 'Livermorium', value: 'Livermorium' },
      { label: 'Tennessine', value: 'Tennessine' },
      { label: 'Oganesson', value: 'Oganesson' },
    ],
  },
];
